# Generated by Django 5.1.4 on 2024-12-23 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gardnerid', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='bookedappointments',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('Gardnerid', models.PositiveIntegerField()),
                ('Dwellerid', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default='00:00')),
                ('slot', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='no action taken', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('appointment_preference', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dweller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100000)),
                ('address', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian pincode.', regex='[0-9]{6}$')])),
                ('description', models.CharField(default='', max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gardner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('phone_number', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('specialization', models.IntegerField(default=0)),
                ('pincode', models.CharField(default=111111, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian pincode.', regex='^[0-9]{6}$')])),
                ('age', models.PositiveIntegerField(default=0)),
                ('experience', models.CharField(default='', max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
                ('officeid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian pincode.', regex='^[0-9]{6}$')])),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pending_Gardners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('phone_number', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
                ('specialization', models.IntegerField(default=0)),
                ('pincode', models.CharField(default=111111, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian pincode.', regex='^[0-9]{6}$')])),
                ('age', models.PositiveIntegerField(default=0)),
                ('experience', models.CharField(default='', max_length=100)),
                ('isdelete', models.BooleanField(default=False)),
                ('officeid', models.IntegerField(default=0)),
            ],
        ),
    ]
